<script setup>
import AppLayout from '@/Layouts/AppLayout.vue'
import SearchableSelect from '@/Components/SearchableSelect.vue'
import Pagination from '@/Components/Pagination.vue'
import EmptyState from '@/Components/EmptyState.vue'
import ConfirmDialog from '@/Components/ConfirmDialog.vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { ref } from 'vue'
import {
    PlusIcon, EyeIcon, TrashIcon, ArrowPathIcon, ArrowDownTrayIcon,
    DocumentDuplicateIcon, KeyIcon,
} from '@heroicons/vue/24/outline'

const props = defineProps({
    papers: Object,
    subjects: Array,
    classes: Array,
    filters: Object,
})

const filters = ref({
    search: props.filters?.search || '',
    subject_id: props.filters?.subject_id || '',
    school_class_id: props.filters?.school_class_id || '',
})

function applyFilters() {
    router.get(route('papers.index'), { ...filters.value }, { preserveState: true, replace: true })
}

const confirmDelete = ref(false)
const toDelete = ref(null)
function askDelete(p) { toDelete.value = p; confirmDelete.value = true }
function doDelete() {
    if (toDelete.value) {
        router.delete(route('papers.destroy', toDelete.value.id), {
            onSuccess: () => { confirmDelete.value = false }
        })
    }
}

function regenerate(p) {
    router.post(route('papers.regenerate', p.id))
}

function formatDate(d) {
    if (!d) return '—'
    try { return new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) }
    catch { return d }
}
</script>

<template>
    <Head title="Paper Generator" />
    <AppLayout :breadcrumbs="[{ label: 'Paper Generator' }]">
        <div class="space-y-4">
            <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                    <h1 class="text-2xl font-bold">Paper Generator</h1>
                    <p class="text-sm text-base-content/60 mt-1">Generate printable question papers from your question bank.</p>
                </div>
                <Link :href="route('papers.generate')" class="btn btn-primary gap-2">
                    <PlusIcon class="w-5 h-5" /> Generate New Paper
                </Link>
            </div>

            <!-- Filters -->
            <div class="card bg-base-100 shadow-md">
                <div class="card-body">
                    <div class="grid grid-cols-1 md:grid-cols-4 gap-3">
                        <div class="md:col-span-2">
                            <input v-model="filters.search" @keyup.enter="applyFilters" type="text"
                                placeholder="Search paper title or exam name..."
                                class="input input-bordered input-sm w-full" />
                        </div>
                        <SearchableSelect v-model="filters.subject_id" size="sm"
                            :options="[{ value: '', label: 'All Subjects' }, ...subjects.map(s => ({ value: s.id, label: s.name }))]"
                            placeholder="All Subjects"
                            @change="applyFilters" />
                        <SearchableSelect v-model="filters.school_class_id" size="sm"
                            :options="[{ value: '', label: 'All Classes' }, ...classes.map(c => ({ value: c.id, label: c.name }))]"
                            placeholder="All Classes"
                            @change="applyFilters" />
                    </div>
                </div>
            </div>

            <!-- List -->
            <div class="card bg-base-100 shadow-md">
                <div class="card-body p-0">
                    <div v-if="papers?.data?.length" class="overflow-x-auto">
                        <table class="table table-zebra table-sm">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Subject</th>
                                    <th>Class</th>
                                    <th>Set</th>
                                    <th>Marks</th>
                                    <th>Duration</th>
                                    <th>Generated by</th>
                                    <th>Date</th>
                                    <th class="text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="p in papers.data" :key="p.id">
                                    <td>
                                        <div class="font-semibold text-sm">{{ p.title }}</div>
                                        <div v-if="p.exam_name" class="text-xs text-base-content/50">{{ p.exam_name }}</div>
                                    </td>
                                    <td class="text-sm">{{ p.subject?.name || '—' }}</td>
                                    <td class="text-sm">{{ p.school_class?.name || '—' }}</td>
                                    <td><span class="badge badge-sm badge-primary">{{ p.set_code }}</span></td>
                                    <td class="text-sm font-mono">{{ p.total_marks }}</td>
                                    <td class="text-xs">{{ p.duration_minutes }} min</td>
                                    <td class="text-xs">{{ p.generator?.name || '—' }}</td>
                                    <td class="text-xs">{{ formatDate(p.created_at) }}</td>
                                    <td class="text-right">
                                        <div class="flex justify-end gap-1">
                                            <Link :href="route('papers.show', p.id)" class="btn btn-ghost btn-xs btn-square" title="View">
                                                <EyeIcon class="w-4 h-4" />
                                            </Link>
                                            <a :href="route('papers.download', p.id)" target="_blank" class="btn btn-ghost btn-xs btn-square" title="Download Paper">
                                                <ArrowDownTrayIcon class="w-4 h-4" />
                                            </a>
                                            <a :href="route('papers.answer-key', p.id)" target="_blank" class="btn btn-ghost btn-xs btn-square text-success" title="Answer Key">
                                                <KeyIcon class="w-4 h-4" />
                                            </a>
                                            <button @click="regenerate(p)" class="btn btn-ghost btn-xs btn-square text-info" title="Regenerate new set">
                                                <ArrowPathIcon class="w-4 h-4" />
                                            </button>
                                            <button @click="askDelete(p)" class="btn btn-ghost btn-xs btn-square text-error" title="Delete">
                                                <TrashIcon class="w-4 h-4" />
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <EmptyState v-else
                        title="No papers generated yet"
                        description="Create your first paper from questions in your bank."
                        action-text="Generate a Paper"
                        :action-href="route('papers.generate')"
                        :icon="DocumentDuplicateIcon" />
                </div>
            </div>

            <div v-if="papers?.data?.length" class="mt-4">
                <Pagination :links="papers.links" :from="papers.from" :to="papers.to" :total="papers.total" />
            </div>
        </div>

        <ConfirmDialog
            :show="confirmDelete"
            title="Delete paper?"
            message="The generated paper record will be removed. Questions in the bank are not affected."
            confirm-text="Delete"
            type="danger"
            @confirm="doDelete"
            @cancel="confirmDelete = false"
        />
    </AppLayout>
</template>
